---
all:
  hosts:
    controller:
      ansible_connection: local
      ansible_user: admin
      ansible_ssh_host: 10.72.5.254
    node1:
      ansible_user: ubuntu
      ansible_ssh_host:  10.72.5.120
    node2:
      ansible_user: ubuntu
      ansible_ssh_host:  10.72.5.121
    node3:
      ansible_user: ubuntu      
      ansible_ssh_host:  10.72.5.130
    node4:
      ansible_user: ubuntu      
      ansible_ssh_host:  10.72.5.131
    node5:
      ansible_user: ubuntu      
      ansible_ssh_host:  10.72.5.132
  children:
    cluster-nodes:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    seed-nodes:
      hosts:
        node1:
        node2:
